name: Build

on:
  push:
    branches:    
      - main
  pull_request:
  # schedule:
  #   - cron: '35 5 * * *'

jobs:
  check_release:
    name: "Check if we should start a new build job for grpcio based on latest release"
    outputs:
      should_build: ${{ steps.grpcio_version.outputs.should_build }}
      latest_version: ${{ steps.grpcio_version.outputs.grpcio_current_version }}
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Check latest available grpcio release
        id: grpcio_version
        run: |
          echo "grpcio_current_version=1.47.2" >> $GITHUB_OUTPUT
          echo "should_build=1" >> $GITHUB_OUTPUT
  
  build_wheels:
    name: Build ${{ matrix.package }} wheels on ${{ matrix.os }}, for Python ${{ matrix.python_build_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macOS-12" ]
        python_build_version: [ "cp38", "cp39", "cp310", "cp311" ]
        package: [ "grpcio" ]

    needs: [check_release]
    if: needs.check_release.outputs.should_build == '1'
    steps:
      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
      
      - name: Download latest ${{ matrix.package }} stable tarball
        run: |
          pip download --no-binary ${{ matrix.package }} ${{ matrix.package }}==${{ needs.check_release.outputs.latest_version }}
          tar xf *.tar.gz
          
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.9.0

      - name: Build wheels
        run: |
          cd ${{ matrix.package }}-*/
          python -m cibuildwheel --output-dir ../wheelhouse
        env:
          CIBW_ARCHS_MACOS: "arm64"
          CIBW_TEST_SKIP: "*_arm64"
          CIBW_BUILD: "${{ matrix.python_build_version }}-macosx_arm64"
          CIBW_BUILD_FRONTEND: pip
          CIBW_ENVIRONMENT_MACOS: "GRPC_PYTHON_BUILD_WITH_CYTHON=1"
          CIBW_BEFORE_BUILD: "pip install Cython; if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "grpcio ${{ needs.check_release.outputs.latest_version }}"
          tag_name: ${{ needs.check_release.outputs.latest_version }}
          files: ./wheelhouse/*.whl
          body: "Apple Silicon built binaries for the grpcio ${{ needs.check_release.outputs.latest_version }} Python library."
